version: '3'
services:
  node:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn dev"
    ports:
      - "8000:3000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql_data:/var/lib/mysql

  redis:
    image: "redis:5.0.5"
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - "./data/redis:/data"

  api:
    depends_on:
      - db
    build: ./api
    ports:
      - 8080:8080
    volumes:
      - ./api:/app_name
    command: sh -c "rm -f tmp/pids/server.pid && rails s -p 8080 -b '0.0.0.0'"
    environment:
      REDIS_URL: redis://redis:6379/0 # redisとの接続に必要

# docker-compose run --rm node yarn create next-app . app --typescript
# docker-compose run --rm api rails new . --api --databese=mysql --slip-bundle
